<div>
    <button id="paytiko-payments-credential-button" onclick="javascript:checkCredential();" class="scalable" type="button"
            id="<?= $block->escapeHtml($block->getHtmlId()); ?>">
        <span>
            <span>
                <span>Check Paytiko credential</span>
            </span>
        </span>
    </button>
    <div id="paytiko-payments-healthcheck">

    </div>
</div>
<style type="text/css">
    #paytiko-payments-healthcheck span {
        padding: 5px 10px;
        text-transform: uppercase;
        display: inline-block;
        color: white !important;
        font-weight: bold;
        border-radius: .25rem;
    }

    #paytiko-payments-healthcheck span.success {
        margin-top: 10px;
        background-color: #28a745;
    }

    #paytiko-payments-healthcheck span.warning {
        margin-top: 10px;
        background-color: #ffc107;
    }

    #paytiko-payments-healthcheck span.error {
        margin-top: 10px;
        background-color: #bf0606;
    }

    #paytiko-payments-healthcheck li {
        line-height: 1.2em;
        border-bottom: dashed 1px #e3e3e3;
        padding: 5px 0;
        font-weight: 600 !important;
    }

    #paytiko-payments-healthcheck li.success {
        color: #155724 !important;
    }

    #paytiko-payments-healthcheck li.warning {
        color: #856404 !important;
    }

    #paytiko-payments-healthcheck li.error {
        color: #bf0606 !important;
    }
</style>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
    //<![CDATA[
    checkCredential = function () {
        

        const environment = document.querySelector('[name="groups[paytiko][fields][environment][value]"]').value;

            let api_url = '';

             if(environment == 'sandbox'){
                 api_url = 'https://qa-core.paytiko.com';
             }
             else if(environment == 'live'){
                  api_url = 'https://core.paytiko.com';
             }

        let statusLabel = {1: "Success", 2: "Warning", 3: "Error", 0: "Success"};
        let htmlcontent = '';
        
        const activationkey = document.querySelector('[name="groups[paytiko][fields][activation_key][value]"]').value;
        const privatekey = document.querySelector('[name="groups[paytiko][fields][private_key][value]"]').value;
        

        
        var baseurlss = "<?= $block->getBaseUrl(); ?>paytiko";
        $.ajax({
                type: 'POST',
                url: baseurlss,
                data: {
                        activationkey: activationkey,
                        privatekey: privatekey,
                        api_url: api_url  
                    },
                dataType: "json",
                cache: false,
                success: function(transport){  
                    console.clear();
                     var Status = transport.status;
                        if(Status == 400) {
                           // let title = "Your details are not valid";
                           let title = JSON.stringify(transport.errors);
                             htmlcontent = '<span class="' + statusLabel[3].toLowerCase() + '">' + title + '</span>';
                            document.getElementById("paytiko-payments-healthcheck").innerHTML = htmlcontent;
                        }else if(Status == 200){
                             var cashierBaseUrl = transport.cashierBaseUrl;
                             var coreBaseUrl = transport.coreBaseUrl;
                             var embedScriptUrl = transport.embedScriptUrl;
                             $("#payment_us_paytiko_cashierBaseUrl").val(cashierBaseUrl);
                             $("#payment_us_paytiko_coreBaseUrl").val(coreBaseUrl);
                             $("#payment_us_paytiko_embedScriptUrl").val(embedScriptUrl);
                             
                              let title = "Your details are valid";
                             htmlcontent = '<span class="' + statusLabel[1].toLowerCase() + '">' + title + '</span>';
                            document.getElementById("paytiko-payments-healthcheck").innerHTML = htmlcontent;
                        }else if(Status == 300){
                            
                              //let title = JSON.stringify(transport.message);
                              let title = 'Wrong API key.';
                             htmlcontent = '<span class="' + statusLabel[3].toLowerCase() + '">' + title + '</span>';
                            document.getElementById("paytiko-payments-healthcheck").innerHTML = htmlcontent;
                        }
                   
                    },
                    error: function(XMLHttpRequest, textStatus, errorThrown) { 
                        console.clear();
                         htmlcontent = '<span class="' + statusLabel[3].toLowerCase() + '">Somthing went wrong. Please contact with Support</span>';
                             document.getElementById("paytiko-payments-healthcheck").innerHTML = htmlcontent;
                    } 
                
                     
            });
    }
});
    //]]>
</script>