<div>
    <button id="paytiko-payment-credential-button" onclick="javascript:checkCredential();" class="scalable" type="button"
            id="<?= $block->escapeHtml($block->getHtmlId()); ?>">
        <span>
            <span>
                <span>Check Paytiko credential</span>
            </span>
        </span>
    </button>
    <div id="paytiko-payment-healthcheck">

    </div>
</div>
<style type="text/css">
    #paytiko-payment-healthcheck span {
        padding: 5px 10px;
        text-transform: uppercase;
        display: inline-block;
        color: white !important;
        font-weight: bold;
        border-radius: .25rem;
    }

    #paytiko-payment-healthcheck span.success {
        margin-top: 10px;
        background-color: #28a745;
    }

    #paytiko-payment-healthcheck span.warning {
        margin-top: 10px;
        background-color: #ffc107;
    }

    #paytiko-payment-healthcheck span.error {
        margin-top: 10px;
        background-color: #bf0606;
    }

    #paytiko-payment-healthcheck li {
        line-height: 1.2em;
        border-bottom: dashed 1px #e3e3e3;
        padding: 5px 0;
        font-weight: 600 !important;
    }

    #paytiko-payment-healthcheck li.success {
        color: #155724 !important;
    }

    #paytiko-payment-healthcheck li.warning {
        color: #856404 !important;
    }

    #paytiko-payment-healthcheck li.error {
        color: #bf0606 !important;
    }
</style>

<script type="text/javascript">
    //<![CDATA[
    checkCredential = function () {
        let statusLabel = {1: "Success", 2: "Warning", 3: "Error", 0: "Success"};
        let htmlcontent = '';
        const inputKey = document.querySelector('[name="groups[paytiko][fields][activation_key][value]"]').value;
        const privatekey = document.querySelector('[name="groups[paytiko][fields][private_key][value]"]').value;
        const healthCheckUrl = '<?= $block->escapeUrl($block->getAjaxHealthCheckUrl()) ?>';
        new Ajax.Request('https://dev-core.paytiko.com/api/cashier/ecommerce/config/'+inputKey, {
            method: 'get',
            requestHeaders: {
                "api-key": privatekey,
                "cache-control": "no-cache"
            },
            
            onComplete: function (transport) {
                    if (transport.responseText.isJSON()) {
                        let response = transport.responseText.evalJSON()
                        let Status = response.status;
                        let Status_transport = transport.status;

                        if(Status == 400) {
                            let title = "Your details are not valid";
                             htmlcontent = '<span class="' + statusLabel[3].toLowerCase() + '">' + title + '</span>';
                            document.getElementById("paytiko-payment-healthcheck").innerHTML = htmlcontent;
                        }else if(Status_transport == 400){
                              let title = "Your details are not valid";
                             htmlcontent = '<span class="' + statusLabel[3].toLowerCase() + '">' + title + '</span>';
                            document.getElementById("paytiko-payment-healthcheck").innerHTML = htmlcontent;
                        }
                        else if(Status_transport == 200){
                              let title = "Details Are Valid";
                             htmlcontent = '<span class="' + statusLabel[1].toLowerCase() + '">' + title + '</span>';
                            document.getElementById("paytiko-payment-healthcheck").innerHTML = htmlcontent;
                        }
                        else if(Status == 200){
                              let title = "Details Are Valid";
                             htmlcontent = '<span class="' + statusLabel[1].toLowerCase() + '">' + title + '</span>';
                            document.getElementById("paytiko-payment-healthcheck").innerHTML = htmlcontent;
                        }
                        else {
                          htmlcontent = '<span class="' + statusLabel[1].toLowerCase() + '">Your Details are Valid!</span>';
                            document.getElementById("paytiko-payment-healthcheck").innerHTML = htmlcontent;
                        }
                 }
            },
            onException: function() { 
                htmlcontent = '<span class="' + statusLabel[3].toLowerCase() + '">Somthing went wrong. Please contact with Support</span>';
                    document.getElementById("paytiko-payment-healthcheck").innerHTML = htmlcontent;
            }

        });
    }
    //]]>
</script>