<style>
    #paytiko-payments-healthcheck span {
        padding: 5px 10px;
        text-transform: uppercase;
        display: inline-block;
        color: white !important;
        font-weight: bold;
        border-radius: .25rem;
    }

    #paytiko-payments-healthcheck span.success {
        margin-top: 10px;
        background-color: #28a745;
    }

    #paytiko-payments-healthcheck span.warning {
        margin-top: 10px;
        background-color: #ffc107;
    }

    #paytiko-payments-healthcheck span.error {
        margin-top: 10px;
        background-color: #bf0606;
    }

    #paytiko-payments-healthcheck li {
        line-height: 1.2em;
        border-bottom: dashed 1px #e3e3e3;
        padding: 5px 0;
        font-weight: 600 !important;
    }

    #paytiko-payments-healthcheck li.success {
        color: #155724 !important;
    }

    #paytiko-payments-healthcheck li.warning {
        color: #856404 !important;
    }

    #paytiko-payments-healthcheck li.error {
        color: #bf0606 !important;
    }
</style>

<div>
    <button id="paytiko-payments-credential-button" onclick="fActivate();" class="scalable" type="button">
        <span>
            <span>
                <span>Paytiko Payments Configuration</span>
            </span>
        </span>
    </button>
    <div id="paytiko-payments-healthcheck"></div>
</div>

<script type="text/javascript">
    var fActivate, showMessage = (msg, style) => {
        document.getElementById('paytiko-payments-healthcheck').innerHTML = `<span class="${style}">${msg}</span>`;
    }
    require(['jquery', 'jquery/ui'], function ($) {
        fActivate = function() {
            const environment   = $('[name="groups[paytiko][fields][environment][value]"]').val();
            const activationKey = $('[name="groups[paytiko][fields][activation_key][value]"]').val();
            const apiKey        = $('[name="groups[paytiko][fields][api_key][value]"]').val();
            const activationUrl = "<?= $block->getBaseUrl(); ?>paytiko";
            $.ajax({
                type: 'POST',
                url: activationUrl,
                data: {activationKey, apiKey, environment},
                dataType: 'json',
                cache: false,
                success: function (data) {
                    let style;
                    if (data.status === 'ok') {
                        $('input[name="groups[paytiko][fields][cashierBaseUrl][value]"]').val(data.cashierBaseUrl);
                        $('input[name="groups[paytiko][fields][coreBaseUrl][value]"]').val(data.coreBaseUrl);
                        $('input[name="groups[paytiko][fields][embedScriptUrl][value]"]').val(data.embedScriptUrl);
                        style = 'success';
                    } else {
                        style = 'error';
                        if (data.errors) {
                            data.message += '<br />' + JSON.stringify(data.errors);
                        }
                    }
                    showMessage(style, data.message);
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    showMessage('error', 'Something went wrong. Check your input or contact support.');
                }
            });
        }
    });
</script>